name: playground
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  algolia_helper_flutter: ^1.1.0
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  hive: ^2.2.3
  infinite_scroll_pagination: ^4.0.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
